### ISSUE TITLE
Changing Meta Key

### ISSUE THREAD

**Issue by rdsalemi** [glyph/E-Max#15]
Hi,

On my Mac and on my VNC-based virtual machine (CentOS) the meta key in E-Max is the command key.  In my VMWARE virtual machine (CentOS) the meta key is the option key on my Mac keyboard.

Is there any way to change the key binding in my VMWARE machine to match the behavior of all my other platforms?

Thanks!

Ray

**Comment by glyph** [comment]
No idea, sorry!  Not really an issue in this package, so closing - but I hope you find your answer.
